config/routes.rb
Couponify::Application.routes.draw do
  
  resources :discount_templates

  resources :discounts, :only => [:index, :show]
  
  match 'statistics'         => "statistics#index"

  root :to                   => 'home#index'

  match 'login'              => 'login#index'

  match 'login/authenticate' => 'login#authenticate'

  match 'login/finalize'     => 'login#finalize'

  match 'login/logout'       => 'login#logout'

end

app/models/discount_template.rb
class DiscountTemplate < ActiveRecord::Base
  
  belongs_to :shop
  has_many :discounts
  has_many :customers, :through => :discounts
  
  validates :shop, :presence => true
  validates :value, :numericality => {:greater_than_or_equal_to => 0}, :allow_nil => false
  validates :discount_type, :inclusion => {:in => ["fixed_amount", "percentage"]}, :allow_nil => false
  validates :customer_criteria, :inclusion => {:in => ["all", "new", "repeat"]}, :allow_nil => false
  
  validates :minimum_order_amount, :numericality => {:greater_than_or_equal_to => 0}, :allow_nil => false
  validates :usage_limit, :numericality => {:greater_than => 0}, :allow_nil => true
  
  validates :valid_type, :inclusion => {:in => ["after_generated", "after_end_date"]}, :allow_nil => true
  validates :days_valid, :numericality => {:greater_than_or_equal_to => 0}, :allow_nil => true
  
  validate :percentage_lte_100
  validate :ends_after_starts
  
  before_validation :nils_to_defaults
  before_validation :dates_to_midnight
  
  attr_accessible :value, :discount_type, :title, :days_valid, :valid_type,
                  :minimum_order_amount, :usage_limit, :customer_criteria,
                  :order_placed_before, :order_placed_after, :shop_id, :shop
                  
  def as_json(options={})
    hash = Hash.new
    hash[:title] = (title.nil? ? "" : title)
    hash[:all_day] = true
    hash[:start] = order_placed_after
    hash[:end] = order_placed_before
    hash[:url] = "discount_templates/#{id}/"
    hash[:id] = id
    return hash
  end
  
  def discount_for_order(order)
    if order.matches? self
      
      d = Discount.new
      
      d.customer = order.customer
      d.discount_template = self
      d.shop = self.shop
      
      unless days_valid.nil?
        if valid_type.eql? "after_end_date"
          d.expires_at = (order_placed_before + days_valid.days).end_of_day
        else
          d.expires_at = days_valid.days.from_now.end_of_day
        end
      end
      
      d.save!
      
      discounts << d
      d
    end
  end
  
  private
    def percentage_lte_100
      self.errors.add(:value, " is over 100%") if (discount_type.eql? "percentage") && (value > 100)
    end
    
    def nils_to_defaults
      self.order_placed_after ||= DateTime.now.utc
      self.minimum_order_amount ||= 0.00
      true
    end
    
    def ends_after_starts
      self.errors.add(:order_placed_before, "is before the start date") if (!order_placed_before.nil? && (order_placed_before < order_placed_after))
    end
    
    def dates_to_midnight
      self.order_placed_after  = self.order_placed_after.utc.beginning_of_day
      
      unless self.order_placed_before.nil?
        self.order_placed_before = self.order_placed_before.utc.end_of_day 
      else 
        self.order_placed_before = self.order_placed_after.end_of_day
      end
    end
end

app/controllers/discount_templates_controller.rb
class DiscountTemplatesController < ApplicationController
  
  around_filter :shopify_session
  
  def index
    @discount_templates = current_shop.discount_templates.all

    respond_to do |format|
      format.html
      format.json do
        render :json => current_shop.discount_templates.where(
          "order_placed_before >= ? && order_placed_after <= ?", 
          Time.at(params[:start].to_i).beginning_of_day, Time.at(params[:end].to_i).end_of_day)
      end
    end
  end

  def show
    @discount_template = current_shop.discount_templates.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  # GET /discount_templates/1/edit
  def edit
    @discount_template = DiscountTemplate.find(params[:id])
    render :layout => nil
  end
  
  def new
    if params[:discount_template]
      @discount_template = DiscountTemplate.new(:order_placed_after => params[:discount_template][:start], :order_placed_before => params[:discount_template][:end])
    else
      @discount_template = DiscountTemplate.new
    end
    render :layout => nil
  end
  
  # POST /discount_templates
  # POST /discount_templates.xml
  def create
    params[:discount_template][:shop_id] = current_shop.id unless params[:discount_template].nil?
    
    @discount_template = DiscountTemplate.new(params[:discount_template])

    respond_to do |format|
      if @discount_template.save
        format.html { redirect_to(discount_templates_path, :notice => 'Discount template was successfully created.') }
        format.js
      else
        @discount_templates = DiscountTemplate.all
        format.html { render :action => "index", :error => 'Oops! Please fix the missing or incorrect details' }
        format.js
      end
    end
  end

  # PUT /discount_templates/1
  # PUT /discount_templates/1.xml
  def update
    @discount_template = DiscountTemplate.find(params[:id])

    respond_to do |format|
      if @discount_template.update_attributes(params[:discount_template])
        format.html { redirect_to(@discount_template, :notice => 'Discount template was successfully updated.') }
        format.js
      else
        format.html { render :action => "edit" }
        format.js
      end
    end
  end

  # DELETE /discount_templates/1
  # DELETE /discount_templates/1.xml
  def destroy
    @discount_template = DiscountTemplate.find(params[:id])
    @discount_template.destroy

    respond_to do |format|
      format.html { redirect_to(discount_templates_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/discount_templates_helper.rb
module DiscountTemplatesHelper
  
  def template_descr(dt)
    d  = "Between <strong>" + (dt.order_placed_after.nil? ? "now " : dt.order_placed_after.strftime("%d %b %y"))
    d += "</strong> and <strong>" + (dt.order_placed_before.nil? ? "forever " : dt.order_placed_before.strftime("%d %b %y"))  + "</strong>"
    d += " send <strong>#{dt.customer_criteria} customers</strong>"
    
    if dt.minimum_order_amount.to_i > 0
       d += " who place <strong> orders over #{dt.minimum_order_amount}USD </strong>"
    end
    
    d += " a <strong>#{value_to_s(dt)}</strong> discount code. "
    d += "This code can be used anytime"
    d += " on <strong> "
    d += dt.usage_limit.nil? ? " one order" : "at most #{pluralize(dt.usage_limit, "order")}"
    d += "</strong>."
  end
  
  def value_to_s(dt)
    if dt.discount_type.eql? "fixed_amount"
      amount_as_currency(dt.value, dt.shop)
    else
      number_to_percentage(dt.value)
    end
  end
  
  def amount_as_currency(amount, shop)
    fmt = shop.money_with_currency_format
    if fmt =~ /\{\{amount_no_decimals\}\}/
      fmt.gsub("{{amount_no_decimals}}", "#{amount}")
    else
      shop.money_with_currency_format.gsub("{{amount}}", pad_number(amount))
    end
  end
  
  def pad_number(number, min_decimals=2)
    s = "%g" % number
    decimals = (s[/\.(\d+)/,1] || "").length
    s << "." if decimals == 0
    s << "0"*[0,min_decimals-decimals].max
  end
  
end

app/views/discount_templates/_form.html.erb
<%= semantic_form_for @discount_template, :html => {:id => "discount_template_form", :class=>"grid8"}, :remote => true do |f| %>
  <%= f.inputs do %>
    <div class="grid8 inline first">
      <%= f.input :title %>
      <p class="dates">
        <% unless @discount_template.order_placed_after.nil? %>
          <%= "Between #{@discount_template.order_placed_after.strftime("%d %b %R")}
        and #{@discount_template.order_placed_before.strftime("%d %b %R")}" %>
        <% end %>
        <%= f.input :order_placed_after, :as => :hidden %>
        <%= f.input :order_placed_before, :as => :hidden %>
      </p>
      <%= f.input :customer_criteria, :as => :select, :collection => ["all","new","repeat"], :required => true, :include_blank => false, :label => "Give" %> customers who spend 
      <% @mao = (@discount_template.minimum_order_amount > 0) unless @discount_template.minimum_order_amount.nil? %>
      <a id="spend_link" style="<%= "display:none" if @mao %>">any amount</a>
      <span id="spend" class="<%= "hide_me" unless @mao %>">
        <%= f.input :minimum_order_amount, :label => "a minimum of #{current_shop.currency}"%>
      </span>
    </div>
    <div class="grid8 inline first">
      <div class="grid4 first">
      <%= f.input :value %>
      </div>
      <div class="grid4 first">
      <%= f.input :discount_type, :as => :select, :collection => [[current_shop.currency, "fixed_amount"], ["%", "percentage"]], :include_blank => false, :label => "" %>
      </div >
    </div>
    <div class="grid8 inline first">
      <% @dv = !(@discount_template.days_valid.nil?) %>
      The coupon <a id="valid_time_link" style="<%= "display:none" if @dv %>">can be used any time</a>
      <span id="valid_time" class="<%= "hide_me" unless @dv %>">
        <%= f.input :days_valid, :label => "is valid until "%>days
      
        <%= f.input :valid_type, :as => :select, :collection => [["after they get the coupon","after_generated"], ["after the promotion finishes", "after_end_date"]], :required => true, :include_blank => false, :label => ""%>
      </span>
    </div>
  <% end %>
  <%= f.buttons %>
<% end %>
<%= javascript_include_tag "discount_template_form" %>

app/views/discount_templates/create.js.erb
<% if @discount_template.errors.any? %>
  $("#discount_template_form > .errors").html("");
  var error_html = "<div class='errors'><h3>Whoops - you'll have to fix some things:</h3><ul>"
  
  <% @discount_template.errors.each do |field, message| %>
    $("#discount_template_<%= field %>_input").parent().parent().removeClass("error").addClass("error");
    error_html += "<li><%= "#{field} #{message}" %></li>"
  <% end %>
  
  $("#discount_template_form").prepend(error_html+"</ul></div>")
<% else %>
  $.fancybox.close()
<% end %>

app/views/discount_templates/edit.html.erb
<%= content_tag :h2, "Edit #{@discount_template.title}"%>

<%= render 'form' %>

app/views/discount_templates/index.html.erb
<% content_for(:head) do %>
  <%= stylesheet_link_tag "fullcalendar", "fullcalendar_changes" %>
  <%= javascript_include_tag "fullcalendar.min.js" %>
<% end %>
<h1>Promotions</h1>

<div id="calendar" class="grid12" ></div>

<div id="popup" class="prefix2 grid8" style="display:none;"></div>
<% content_for(:jquery) do %>

  $("#fancybox-outer").addClass("container12");
  
  var date = new Date();
	var d = date.getDate();
	var m = date.getMonth();
	var y = date.getFullYear();
	
	function postDate(event){
	  end = event.end
	  if(end != null){
	    end = end.toDateString();
	  }
	  $.ajax({
       type: "POST",
       url: event.url,
       data: { _method:'PUT', discount_template: {order_placed_before: end, order_placed_after: event.start.toDateString()}},
       success: function(msg){
       }
     });
	}
	
	var calendar = $('#calendar').fullCalendar({
		header: {
			left: 'prev,next today',
			center: 'title',
			right: ''
		},
		selectable: true,
		selectHelper: true,
		firstDay: 1,
		aspectRatio: 2,
		select: function(start, end, allDay) {
			$.fancybox({
        'autoDimensions': false,
        'width': 630,
        'height': 400,
        'transitionIn': 'none',
        'transitionOut': 'none',
        'type': 'ajax',
        'href': "discount_templates/new?discount_template[start]="+start.toDateString()+"&discount_template[end]="+end.toDateString(),
        'onClosed': function(){
          $("#calendar").fullCalendar('refetchEvents');
      }});
		},
		eventRender: function(event, element) {
		  $(element).attr('id', 'fc_event_'+event.id);
		  $(element).attr('title', 'Click to edit '+event.title);
		},
		events: 'discount_templates.json',
		ignoreTimezone: false,
		eventClick: function(event) {
      if (event.url) {
        $.fancybox({
            'autoDimensions': false,
            'width': 630,
            'height': 400,
            'transitionIn': 'none',
            'transitionOut': 'none',
            'type': 'ajax',
            'href': event.url+"edit",
            'onClosed': function(){
              $("#calendar").fullCalendar('refetchEvents');
            }
        });
        return false;
      }
    },
		editable: true,
		eventDrop: function(event,dayDelta,minuteDelta,allDay,revertFunc) {
		  postDate(event);
     },
    eventResize: function(event,dayDelta,minuteDelta,allDay,revertFunc) {
 		  postDate(event);
    }
	});
<% end %>

app/views/discount_templates/new.html.erb
<h1>New discount_template</h1>

<%= render 'form' %>

<%= link_to 'Back', discount_templates_path %>

app/views/discount_templates/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'form' %>

<%= link_to 'Edit', edit_discount_template_path(@discount_template) %> |
<%= link_to 'Back', discount_templates_path %>

app/views/discount_templates/update.js.erb
<% if @discount_template.errors.any? %>
  $("#discount_template_form > .errors").html("");
  var error_html = "<div class='errors'><h3>Whoops - you'll have to fix some things:</h3><ul>"
  
  <% @discount_template.errors.each do |field, message| %>
    $("#discount_template_<%= field %>_input").parent().parent().removeClass("error").addClass("error");
    error_html += "<li><%= "#{field} #{message}" %></li>"
  <% end %>
  
  $("#discount_template_form").prepend(error_html+"</ul></div>")
<% else %>
  $.fancybox.close()
<% end %>