config/routes.rb
Couponify::Application.routes.draw do
  
  resources :discount_templates

  resources :discounts, :only => [:index, :show]
  
  match 'statistics'         => "statistics#index"

  root :to                   => 'home#index'

  match 'login'              => 'login#index'

  match 'login/authenticate' => 'login#authenticate'

  match 'login/finalize'     => 'login#finalize'

  match 'login/logout'       => 'login#logout'

end

app/models/discount.rb
class Discount < ActiveRecord::Base
  
  belongs_to :shop
  belongs_to :customer
  belongs_to :discount_template
  
  validates :customer, :presence => true
  validates :discount_template, :presence => true
  validates_uniqueness_of :code, :scope => :customer_id
  validates :shop, :presence => true
  
  scope :used, where("used = ?", true)
  scope :unused, where("used IS NOT true")
  
  def initialize(*args)
    super(*args)
    
    o = [('a'..'z'),('A'..'Z'),('0'..'9')].map{|i| i.to_a}.flatten;  
    self.code = (0..9).map{ o[rand(o.length)] }.join;
  end
  
end

app/controllers/discounts_controller.rb
class DiscountsController < ApplicationController
  
  around_filter :shopify_session
  
  def index
    @discounts = current_shop.discounts.all

    respond_to do |format|
      format.html
    end
  end

  def show
    @discount = current_shop.discounts.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/views/discounts/index.html.erb
<h1>Listing discounts</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Customer</th>
    <th>Used?</th>
  </tr>

<% @discounts.each do |discount| %>
  <tr>
    <td><%= discount.code %></td>
    <td><%= discount.customer.email %></td>
    <td><%= discount.used? %></td>
    <td><%= link_to 'Show', discount %></td>
  </tr>
<% end %>
</table>

app/views/discounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @discount.code %>
</p>

<p>
  <b>Allocated to:</b>
  <%= link_to @discount.customer.name, @discount.customer.shopify_url %>
</p>

<p>
  <b>Template:</b>
  <%= sanitize template_descr(@discount.discount_template) %>
</p>



<%= link_to 'Back', discounts_path %>