config/routes.rb
Couponify::Application.routes.draw do
  
  resources :discount_templates

  resources :discounts, :only => [:index, :show]
  
  match 'statistics'         => "statistics#index"

  root :to                   => 'home#index'

  match 'login'              => 'login#index'

  match 'login/authenticate' => 'login#authenticate'

  match 'login/finalize'     => 'login#finalize'

  match 'login/logout'       => 'login#logout'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shopify Application</title>
  <%= stylesheet_link_tag "reset", "cupertino/jquery-ui-1.8.13.custom.css", "960", "formtastic", "fancybox", "jquery.jqplot.css", "style" %>
  
  <!--[if lt IE 9]><script language="javascript" type="text/javascript" src="/javascripts/jqplot/excanvas.js"></script><![endif]-->
  <%= javascript_include_tag "application", "jquery-1.6.1.min.js", "rails", "jquery-ui-1.8.14.custom.min.js", "jquery.fancybox-1.3.4.pack", "jqplot/jquery.jqplot.min.js" %>
  
  <%= csrf_meta_tag %>
  <%= content_for(:head) %>
</head>

<body>
  <div id="header">
    <div class="container12">
      <div class="grid12">
        <h1> <%= link_to (image_tag "banner.png", :alt=>"couponify"), root_url, :class=> "logo", :name=>"couponify" %></h1>
        <ul id="tabs">
          <% if current_shop %>
            <li>
              <%= link_to 'Statistics', statistics_path %>
            </li>
            <li>
              <%= link_to 'Promotions', discount_templates_path %>
            </li>
            <li>
              <%= link_to "Shopify", "https://#{current_shop.domain}/admin", :class => 'shop_name' %>
            </li>
          <% else %>
            <li>
              <%= link_to 'Log In', login_path %>
            </li>
          <% end %>
          <li>
            <%= link_to "Help", root_url %>
          </li>
        </ul>
      </div>
    </div>
  </div>
  
  <div class="content container12">
    <!-- Flash error & notice-->
    <% if flash[:error] %> <div id="flasherrors"><%= flash[:error] %></div><% end %>
    <% if flash[:notice] %><div id="flashnotices"><%= flash[:notice] %></div><% end %>

    <!-- begin div.main-->
    <div id="main" class="grid12">
      <%= yield %>
    </div>
    <!-- end div.main -->
  </div>
  
  <div class="clear"></div>
  
  <script>
  $(document).ready(
    function(){
      <%= content_for(:jquery) %>
    });
  </script>
</body>
</html>

app/views/layouts/popup.html.erb
<div class="prefix2 grid8 rounded" style="background-color: #fff;">
  <%= yield %>
</div>
  